spring:
  profiles:
    active: local
server:
  port: 8083
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

---
spring:
  flyway:
    enabled: true
    username: sa
    locations: filesystem:migration
    ignore-missing-migrations: true
    validate-on-migrate: false
    baseline-on-migrate: true
    encoding: UTF-8
  h2:
  console:
    enabled: true
    path: /h2-console
    settings:
      trace: false
      web-allow-others: false
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework: debug
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace