create table customer (
   id bigint generated by default as identity,
    role varchar(255),
    email clob,
    last_login_date timestamp,
    name varchar(200),
    password varchar(255),
    primary key (id)
)